
    create table clientes (
        data_criacao timestamp(6),
        data_modificacao timestamp(6),
        id bigint generated by default as identity,
        usuario_id bigint not null unique,
        cpf varchar(11) not null unique,
        telefone varchar(15) not null unique,
        nome varchar(100) not null,
        criado_por varchar(255),
        modificado_por varchar(255),
        primary key (id)
    );

    create table usuarios (
        activated boolean,
        data_criacao timestamp(6),
        data_modificacao timestamp(6),
        id bigint generated by default as identity,
        username varchar(100) not null unique,
        password varchar(200) not null,
        criado_por varchar(255),
        modificado_por varchar(255),
        role enum ('ROLE_ADMIN','ROLE_CLIENTE') not null,
        primary key (id)
    );

    alter table if exists clientes 
       add constraint FKk6iwsq3kts1bblivkjy6epajx 
       foreign key (usuario_id) 
       references usuarios;
