
    create table clientes (
        data_criacao timestamp(6),
        data_modificacao timestamp(6),
        id bigint generated by default as identity,
        usuario_id bigint not null unique,
        cpf varchar(14) not null unique,
        telefone varchar(15) not null unique,
        nome varchar(100) not null,
        criado_por varchar(255),
        modificado_por varchar(255),
        primary key (id)
    );

    create table reservations (
        end_time timestamp(6) not null,
        id bigint generated by default as identity,
        resource_id bigint not null,
        start_time timestamp(6) not null,
        user_id bigint not null,
        primary key (id)
    );

    create table resources (
        id bigint generated by default as identity,
        name varchar(255) not null unique,
        status varchar(255) not null,
        type varchar(255),
        primary key (id)
    );

    create table usuarios (
        activated boolean,
        data_criacao timestamp(6),
        data_modificacao timestamp(6),
        id bigint generated by default as identity,
        role varchar(25) not null check (role in ('ROLE_ADMIN','ROLE_CLIENTE')),
        username varchar(100) not null unique,
        password varchar(200) not null,
        criado_por varchar(255),
        modificado_por varchar(255),
        primary key (id)
    );

    alter table if exists clientes 
       add constraint FKk6iwsq3kts1bblivkjy6epajx 
       foreign key (usuario_id) 
       references usuarios;

    alter table if exists reservations 
       add constraint FKcuu9fjca4p9mplpssqwaopdea 
       foreign key (resource_id) 
       references resources;

    alter table if exists reservations 
       add constraint FKtq452en54tt29rrveicd2k231 
       foreign key (user_id) 
       references usuarios;
