
    create table clientes (
        data_criacao timestamp(6),
        data_modificacao timestamp(6),
        id bigint generated by default as identity,
        usuario_id bigint not null unique,
        cpf varchar(14) not null unique,
        telefone varchar(15) not null unique,
        nome varchar(100) not null,
        criado_por varchar(255),
        modificado_por varchar(255),
        primary key (id)
    );

    create table recursos (
        numero_vaga integer not null unique,
        id bigint generated by default as identity,
        nome varchar(255) not null unique,
        status varchar(255) not null,
        tipo varchar(255) check (tipo in ('CARRO_PEQUENO','CARRO_GRANDE','MOTO','VAGA_PRIORIDADE','VAGA_PCD','VAGA_ELETRICA')),
        primary key (id)
    );

    create table reservas (
        horario_fim timestamp(6) not null,
        horario_inicio timestamp(6) not null,
        id bigint generated by default as identity,
        recurso_id bigint not null,
        usuario_id bigint not null,
        primary key (id)
    );

    create table usuarios (
        activated boolean,
        data_criacao timestamp(6),
        data_modificacao timestamp(6),
        id bigint generated by default as identity,
        role varchar(25) not null check (role in ('ROLE_ADMIN','ROLE_CLIENTE')),
        username varchar(100) not null unique,
        password varchar(200) not null,
        criado_por varchar(255),
        modificado_por varchar(255),
        primary key (id)
    );

    create table veiculos (
        id bigint generated by default as identity,
        usuario_id bigint not null,
        marca varchar(255) not null,
        modelo varchar(255) not null,
        placa varchar(255) not null unique,
        primary key (id)
    );

    alter table if exists clientes 
       add constraint FKk6iwsq3kts1bblivkjy6epajx 
       foreign key (usuario_id) 
       references usuarios;

    alter table if exists reservas 
       add constraint FKinumgn7htlywdgrk7tvdc73ot 
       foreign key (recurso_id) 
       references recursos;

    alter table if exists reservas 
       add constraint FKcfh7qcr7oxomqk5hhbxdg2m7p 
       foreign key (usuario_id) 
       references usuarios;

    alter table if exists veiculos 
       add constraint FKnnndigwhb1kq7kywnlib68umq 
       foreign key (usuario_id) 
       references usuarios;
