create table usuarios (
    activated boolean,
    data_criacao timestamp(6),
    data_modificacao timestamp(6),
    id bigint generated by default as identity,
    username varchar(100) not null unique,
    password varchar(200) not null,
    criado_por varchar(255),
    modificado_por varchar(255),
    role varchar(50) not null,
    primary key (id)
);