create table clientes (
    data_criacao timestamp(6),
    data_modificacao timestamp(6),
    id bigint generated by default as identity,
    usuario_id bigint not null unique,
    cpf varchar(14) not null unique,
    telefone varchar(15) not null unique,
    nome varchar(100) not null,
    criado_por varchar(255),
    modificado_por varchar(255),
    primary key (id)
);