create table reservations (
  end_time timestamp(6) not null,
  id bigint generated by default as identity,
  resource_id bigint not null,
  start_time timestamp(6) not null,
  user_id bigint not null,
  primary key (id)
);