create table reservas (
    horario_fim timestamp(6),
    horario_inicio timestamp(6) not null,
    id bigint generated by default as identity,
    recurso_id bigint not null,
    usuario_id bigint not null,
    veiculo_id bigint not null,
    primary key (id)
);