create table recursos (
    numero_vaga integer not null unique,
    id bigint generated by default as identity,
    nome varchar(255) not null unique,
    status varchar(255) not null,
    tipo varchar(255) check (tipo in ('CARRO_PEQUENO','CARRO_GRANDE','MOTO','VAGA_PRIORIDADE','VAGA_PCD','VAGA_ELETRICA')),
    primary key (id)
);