create table veiculos (
    id bigint generated by default as identity,
    usuario_id bigint not null,
    marca varchar(255) not null,
    modelo varchar(255) not null,
    placa varchar(255) not null unique,
    primary key (id)
);