# LOCALE
spring.web.locale-resolver=fixed
spring.web.locale=pt_BR

server.ssl.enabled=false

# Datasource H2 em memória
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=

# Ativar Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Springdoc OpenApi 3.1 & Swagger 3
springdoc.swagger-ui.path=/docs-park.html
springdoc.api-docs.path=/docs-park
springdoc.packagesToScan=br.edu.ifba.park.iot.backend.web.controller, br.edu.ifba.park.iot.backend.security.web.controller

# Configuração do Log do Sistema 
logging.level.root=WARN
logging.level.org.springframework.web=DEBUG
logging.level.com.swprojects.parkapi=INFO

logging.file.name=myapp.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=10

# CRIA O SCRIPT DO SGBD
# spring.jpa.properties.javax.persistence.schema-generation.create-source=metadata
# spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
# spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=create.sql
# spring.jpa.properties.hibernate.hbm2ddl.delimiter=;