# LOCALE
spring.web.locale-resolver=fixed
spring.web.locale=pt_BR

server.ssl.enabled=false

# POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/park_api?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${POSTGRES_DATASOURCE_USER}
spring.datasource.password=${POSTGRES_DATASOURCE_PASSWORD}
logging.level.org.springframework=DEBUG
logging.level.org.flywaydb=DEBUG

#JPA
# spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
# spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.format_sql=true

# Configurações do Flyway para migrações de banco de dados
spring.flyway.enabled=true

# Configurações para o Spring Boot ler o data.sql as migrações
# Não esquecer de mudar de always para never
spring.sql.init.mode=always
spring.sql.init.platform=postgres
spring.sql.init.data-locations=classpath:db/data/S*__*.sql

# Springdoc OpenApi 3.1 & Swagger 3
springdoc.swagger-ui.path=/docs-park.html
springdoc.api-docs.path=/docs-park
springdoc.packagesToScan=br.edu.ifba.park.iot.backend.web.controller, br.edu.ifba.park.iot.backend.security.web.controller

# Configuração do Log do Sistema 
logging.level.root=WARN
logging.level.org.springframework.web=DEBUG
logging.level.com.swprojects.parkapi=INFO

logging.file.name=myapp.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=10

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

spring.freemarker.template-loader-path=classpath:/templates/
spring.freemarker.suffix=.html

# CRIA O SCRIPT DO SGBD
spring.jpa.properties.javax.persistence.schema-generation.create-source=metadata
spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=create.sql
spring.jpa.properties.hibernate.hbm2ddl.delimiter=;
# spring.jpa.properties.hibernate.format_sql=true